# Generated by Django 3.0.6 on 2020-05-25 20:02

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        BtreeGinExtension(),

        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.PositiveIntegerField(unique=True)),
                ('authors', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('sv', django.contrib.postgres.search.SearchVectorField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='stuff.Work')),
            ],
            options={
                'ordering': ('work', 'ordinal'),
            },
        ),
        migrations.AddIndex(
            model_name='row',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sv'], name='stuff_row_sv_82bcfb_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='row',
            unique_together={('work', 'ordinal')},
        ),
    ]
